"""Project manifest and invariant checks.

``.react-dev.json`` records what a project was generated from, which is what
makes ``react-dev sync`` and ``react-dev doctor`` possible at all: without a
version stamp you can never tell which generation of the workflow a repo is on,
so fleet-wide fixes are impossible.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from datetime import date
from pathlib import Path

#: Directories never part of a template fingerprint.
_FINGERPRINT_SKIP = {
    "node_modules", "dist", "coverage", "playwright-report", "test-results",
    "storybook-static", ".expo", "__pycache__", ".git",
}


def template_fingerprint(template_root: Path) -> str:
    """Content hash of a template tree.

    A hand-maintained version number cannot detect template drift -- it was
    stamped 1.0.0 through a dozen breaking template changes, so the one check
    meant to catch drift reported "template and CLI both 1.0.0" on a project
    missing six generator targets and all of MSW.

    This cannot be forgotten: it changes whenever any template file changes.
    """
    digest = hashlib.sha256()
    for path in sorted(p for p in template_root.rglob("*") if p.is_file()):
        if any(part in _FINGERPRINT_SKIP for part in path.parts):
            continue
        digest.update(str(path.relative_to(template_root)).encode())
        digest.update(path.read_bytes())
    return digest.hexdigest()[:16]

MANIFEST = ".react-dev.json"

#: Files the user is expected to edit. ``sync`` never overwrites these.
USER_OWNED = ("AGENTS.md",)


def write_manifest(project: Path, *, cli_version: str, project_type: str,
                   agents: list[str], skills: list[str],
                   fingerprint: str | None = None) -> None:
    (project / MANIFEST).write_text(
        json.dumps(
            {
                "cliVersion": cli_version,
                "templateFingerprint": fingerprint,
                "projectType": project_type,
                "agents": agents,
                "skills": sorted(skills),
                "createdAt": date.today().isoformat(),
                "userOwned": list(USER_OWNED),
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )


def read_manifest(project: Path) -> dict | None:
    path = project / MANIFEST
    if not path.is_file():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return None


#: What the currently-installed skills instruct the agent to use. A project
#: whose template predates any of these will have an agent running commands
#: that do not exist, so `doctor` checks for them explicitly.
#:
#: Add an entry here whenever a skill starts depending on new template surface.
REQUIRED_SCRIPTS: tuple[tuple[str, str], ...] = (
    ("verify", "the single gate every skill ends with"),
    ("typecheck", "tsc -b"),
    ("test", "unit tests"),
    ("e2e", "Playwright flows"),
    ("a11y", "axe"),
    ("visual", "screenshot baselines (react-verify step 4)"),
    ("lint:rules", "tests for promoted ESLint rules (react-feedback)"),
    ("duplicates", "jscpd"),
    ("i18n:check", "locale parity (react-i18n)"),
    ("gen", "the deterministic generator"),
)

#: Generator targets the skills name directly.
REQUIRED_GEN_TARGETS: tuple[str, ...] = (
    "feature", "component", "hook", "page",
    "atom", "molecule", "organism", "template",
    "promote", "mock",
)

#: Template surface the skills write into.
REQUIRED_PATHS: tuple[tuple[str, str], ...] = (
    ("src/testing/mocks/handlers/index.ts", "the one composed MSW handler list"),
    ("src/testing/mocks/server.ts", "MSW for Vitest"),
    ("src/testing/mocks/browser.ts", "MSW for dev and Storybook"),
    ("public/mockServiceWorker.js", "generated by `npx msw init public`"),
    ("src/components/atoms", "atomic layer"),
    ("src/components/molecules", "atomic layer"),
    ("src/components/organisms", "atomic layer"),
    ("src/components/templates", "atomic layer"),
    ("components.json", "shadcn registry config (react-component)"),
    ("eslint-rules/index.js", "where react-feedback promotes a rule"),
)


@dataclass
class Finding:
    level: str  # "error" | "warn" | "ok"
    check: str
    detail: str


def _pkg_scripts(project: Path) -> dict[str, str]:
    pkg = project / "package.json"
    if not pkg.is_file():
        return {}
    try:
        return json.loads(pkg.read_text(encoding="utf-8")).get("scripts", {})
    except json.JSONDecodeError:
        return {}


def diagnose(project: Path, cli_version: str = "?",
             template_root: Path | None = None) -> list[Finding]:
    """Check a generated project against the invariants the workflow relies on.

    Each check maps to a finding in ENTERPRISE-READINESS-AUDIT.md -- these are
    precisely the things that, when missing, make agent output unverifiable.
    """
    out: list[Finding] = []

    def add(ok: bool, check: str, detail_ok: str, detail_bad: str, level: str = "error"):
        out.append(Finding("ok" if ok else level, check, detail_ok if ok else detail_bad))

    manifest = read_manifest(project)
    add(manifest is not None, "manifest",
        f"{MANIFEST} v{(manifest or {}).get('cliVersion', '?')}",
        f"{MANIFEST} missing - run `react-dev sync`", level="warn")

    # --- template fingerprint -------------------------------------------------
    # Content-based, so it catches drift a forgotten version bump would hide.
    if manifest is not None and template_root is not None and template_root.is_dir():
        stamped_fp = manifest.get("templateFingerprint")
        current_fp = template_fingerprint(template_root)
        if stamped_fp is None:
            add(False, "template fingerprint", "",
                "not stamped (project predates fingerprinting) - run "
                "`react-dev sync --with-template`", level="warn")
        else:
            add(stamped_fp == current_fp, "template fingerprint",
                f"matches the installed template ({current_fp})",
                f"project {stamped_fp} vs installed {current_fp} - the template "
                "changed since this project was made. "
                "Run `react-dev sync --with-template`.",
                level="warn")

    # --- version skew ---------------------------------------------------------
    # `sync` refreshes skills and agent wiring but deliberately never touches
    # project code, so an older project can end up with new skills and an old
    # template. That combination fails silently: the agent runs a command the
    # project does not have.
    if manifest is not None:
        stamped = str(manifest.get("cliVersion", "?"))
        add(stamped == cli_version, "cli version",
            f"template and CLI both {cli_version}",
            f"template stamped {stamped}, CLI is {cli_version}. `sync` updates "
            "skills but NOT project code - check the capability rows below.",
            level="warn")

    # --- capabilities the current skills require ------------------------------
    scripts = _pkg_scripts(project)
    for name, why in REQUIRED_SCRIPTS:
        add(name in scripts, f"npm run {name}", scripts.get(name, ""),
            f"missing - {why}")

    generator = project / "tools" / "gen" / "index.mjs"
    if generator.is_file():
        source = generator.read_text(encoding="utf-8", errors="ignore")
        missing = [g for g in REQUIRED_GEN_TARGETS if f"{g}:" not in source]
        add(not missing, "generator targets",
            f"all {len(REQUIRED_GEN_TARGETS)} present",
            f"missing: {', '.join(missing)} - skills reference these, so the "
            "agent will run commands that do not exist")
    else:
        add(False, "generator targets", "", "tools/gen/index.mjs missing")

    for rel, why in REQUIRED_PATHS:
        add((project / rel).exists(), rel, "present", f"missing - {why}")

    # --- agent wiring -------------------------------------------------------
    skills_dir = project / ".agents" / "skills"
    skills = sorted(p.name for p in skills_dir.glob("*/SKILL.md")) if skills_dir.is_dir() else []
    add(bool(skills), "skills", f"{len(skills)} canonical skills in .agents/skills/",
        ".agents/skills/ missing or empty - run `react-dev sync`")

    agents_md = project / "AGENTS.md"
    add(agents_md.is_file(), "AGENTS.md", f"{agents_md.stat().st_size if agents_md.is_file() else 0} bytes",
        "AGENTS.md missing - the agent has no project rules")
    if agents_md.is_file():
        size = agents_md.stat().st_size
        add(size <= 8192, "AGENTS.md size", f"{size} B (under the 8 KiB guideline)",
            f"{size} B - over 8 KiB; Codex caps at project_doc_max_bytes (32 KiB) "
            "and long rules get skimmed. Move detail into a skill reference.",
            level="warn")

    for link, target in (("CLAUDE.md", "AGENTS.md"), ("GEMINI.md", "AGENTS.md")):
        p = project / link
        add(p.exists(), f"{link}", f"present -> {target}",
            f"{link} missing - that agent will not read the constitution",
            level="warn")

    # --- CI -------------------------------------------------------------------
    add((project / ".github" / "workflows").is_dir(), "CI",
        "workflow present", "no .github/workflows - nothing gates a merge", level="warn")

    # --- architecture enforcement ------------------------------------------
    eslint = next((p for p in project.glob("eslint.config.*")), None)
    add(eslint is not None, "eslint config", eslint.name if eslint else "",
        "no flat eslint config - `npm run lint` cannot run")
    if eslint is not None:
        text = eslint.read_text(encoding="utf-8")
        add("boundaries" in text, "layer boundaries",
            "eslint-plugin-boundaries wired in",
            "boundaries not enforced - nothing stops cross-feature imports", level="warn")

    add((project / "src" / "features").is_dir() or (project / "app").is_dir(),
        "feature slices", "src/features/ present",
        "no src/features/ - code will pile into shared buckets", level="warn")

    # --- feedback loop ------------------------------------------------------
    add((project / ".ai").is_dir(), "feedback loop",
        ".ai/ present", ".ai/ missing - feedback has nowhere durable to land", level="warn")
    add((project / "specs").is_dir(), "specs",
        "specs/ present", "specs/ missing - no per-feature traceability", level="warn")

    # --- hygiene ------------------------------------------------------------
    src = project / "src"
    if src.is_dir():
        hits = [
            f"{p.relative_to(project)}"
            for p in src.rglob("*.ts*")
            if any(tok in p.read_text(encoding="utf-8", errors="ignore")
                   for tok in ("as any", "@ts-ignore", "@ts-nocheck"))
        ]
        add(not hits, "no type escapes", "clean",
            f"{len(hits)} file(s) use as any/@ts-ignore: {', '.join(hits[:3])}"
            + (" ..." if len(hits) > 3 else ""), level="warn")

    return out
