// react-dev:generated by `npm run port` -- every lucide icon this app imports (none yet).
import type { ComponentType } from 'react';
import type { LucideProps } from 'lucide-react-native';
export type { LucideProps } from 'lucide-react-native';
export type LucideIcon = ComponentType<LucideProps>;
