// react-dev:route generated by `npm run port` from the web route '/'.
import { Stack } from 'expo-router';
import { useTranslation } from 'react-i18next';
import Page from '@/screens/home';

export default function Route() {
  const { t } = useTranslation('nav');
  return (
    <>
      <Stack.Screen options={{ title: t('home') }} />
      <Page />
    </>
  );
}
