import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

/**
 * The web app's env module, made to read Expo's environment instead of Vite's.
 *
 * Everything that matters in that file -- the schema, the defaults, the error
 * message a misconfigured build fails with -- is kept byte for byte. Only the
 * SOURCE changes: `import.meta.env` becomes an object of literal
 * `process.env.EXPO_PUBLIC_*` reads, which is the one form Expo inlines into a
 * bundle (`process.env[name]` is NOT inlined and comes back undefined).
 *
 * The exported keys keep their web names (`VITE_API_URL`), so every copied file
 * that reads `env.VITE_API_URL` works unchanged. The prefix is a web leftover;
 * renaming it would mean editing every importer, which is the opposite of a copy.
 */
export const GENERATED_HEADER =
  '// react-dev:generated by `npm run port` from the web app. Edit the web file and re-run the port.\n';

export function expoName(viteName) {
  return `EXPO_PUBLIC_${viteName.replace(/^VITE_/, '')}`;
}

export function nativeEnvModule(webText) {
  const names = [...new Set(webText.match(/\bVITE_[A-Z0-9_]+\b/g) ?? [])].sort();
  const source = [
    '/**',
    ' * Expo inlines `process.env.EXPO_PUBLIC_X` -- written out literally -- at build time.',
    ' * The keys keep their web names so every copied file reads them unchanged.',
    ' */',
    'const expoEnv = {',
    ...names.map((name) => `  ${name}: process.env.${expoName(name)},`),
    '};',
    '',
  ].join('\n');

  // Static imports must stay first; the source object goes after them.
  const lines = webText.split('\n');
  let lastImport = -1;
  lines.forEach((line, index) => {
    if (/^import\s/.test(line) || (lastImport === index - 1 && /^\s+\S.*from\s+['"]/.test(line)))
      lastImport = index;
  });
  const head = lines.slice(0, lastImport + 1).join('\n');
  const body = lines
    .slice(lastImport + 1)
    .join('\n')
    .replace(/import\.meta\.env\.(VITE_[A-Z0-9_]+)/g, 'expoEnv.$1')
    .replace(/import\.meta\.env\[(['"])(VITE_[A-Z0-9_]+)\1\]/g, 'expoEnv.$2')
    .replace(/import\.meta\.env/g, 'expoEnv');

  return `${GENERATED_HEADER}${head}${head ? '\n\n' : ''}${source}${body.replace(/^\n+/, '')}`;
}

/** `.env.development` with every VITE_X renamed EXPO_PUBLIC_X, comments kept. */
export function nativeDotEnv(webText) {
  return webText
    .split('\n')
    .map((line) => line.replace(/^(\s*#?\s*)VITE_([A-Z0-9_]+)=/, '$1EXPO_PUBLIC_$2='))
    .join('\n')
    .replace(/Vite\b/g, 'Expo')
    .replace(/VITE_/g, 'EXPO_PUBLIC_');
}

export function readWebEnv(webRoot) {
  const path = join(webRoot, 'src/config/env.ts');
  return existsSync(path) ? readFileSync(path, 'utf8') : null;
}
