import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { listFiles } from './classify.mjs';
import { scanSource } from './scan.mjs';

/** lucide's type-level exports: re-exported as types, never wrapped. */
const TYPES = new Set([
  'LucideIcon',
  'LucideProps',
  'IconNode',
  'LucideIconNode',
  'LucideIconData',
]);

/**
 * Every icon name the app uses: imported from lucide-react anywhere on the web
 * side (so a translation can use any of them), or from `@/platform/icons`
 * anywhere natively (an icon a translation added).
 */
export function iconNames(webRoot, nativeRoot) {
  const names = new Set();
  const collect = (root, from) => {
    for (const rel of listFiles(root)) {
      if (!/\.tsx?$/.test(rel) || rel.endsWith('.d.ts') || rel === 'src/platform/icons.ts')
        continue;
      const text = readFileSync(join(root, rel), 'utf8');
      if (!text.includes(from)) continue;
      for (const item of scanSource(join(root, rel), text).imports)
        if (item.specifier === from) for (const name of item.members) names.add(name);
    }
  };
  collect(webRoot, 'lucide-react');
  if (existsSync(join(nativeRoot, 'src'))) collect(nativeRoot, '@/platform/icons');
  return [...names].filter((name) => !TYPES.has(name)).sort();
}

export function iconsModule(names) {
  // No lucide icons in the app yet: the types, and nothing to wrap.
  const types = [
    '/**',
    " * lucide-react-native's props, plus the attributes the web puts on decorative",
    ' * icons (`aria-hidden="true" focusable="false"`). A native SVG is neither',
    ' * announced nor focusable, so they are accepted and dropped.',
    ' */',
    "export type LucideProps = Omit<GlyphProps, 'focusable' | 'aria-hidden'> & {",
    "  'aria-hidden'?: boolean | 'true' | 'false';",
    "  focusable?: boolean | 'true' | 'false';",
    '};',
    '',
    '/** What every export here is: an icon that takes className. Copied code types icon maps with it. */',
    'export type LucideIcon = ComponentType<LucideProps>;',
  ];
  if (names.length === 0) {
    return [
      '// react-dev:generated by `npm run port` -- every lucide icon this app imports (none yet).',
      "import type { ComponentType } from 'react';",
      "import type { LucideProps as GlyphProps } from 'lucide-react-native';",
      '',
      ...types,
      '',
    ].join('\n');
  }
  const lines = [
    '// react-dev:generated by `npm run port` -- every lucide icon this app imports.',
    '/**',
    ' * Copied web code imports icons from here (the port rewrites `lucide-react`).',
    ' * Each is lucide-react-native wrapped with withUniwind, so the classes the web',
    ' * sizes and colours icons with keep working: `size-5` sets the size,',
    ' * `text-primary` the stroke colour, `fill-current` the fill. Add an icon by',
    ' * importing it from here in a translated file and re-running the port.',
    ' */',
    "import { createElement, type ComponentType } from 'react';",
    "import type { LucideProps as GlyphProps } from 'lucide-react-native';",
    "import { withUniwind } from 'uniwind';",
  ];
  if (names.length > 0) {
    lines.push(
      `import { ${names.map((name) => `${name} as ${name}Glyph`).join(', ')} } from 'lucide-react-native';`,
    );
  }
  lines.push(
    '',
    ...types,
    '',
    '/**',
    ' * withUniwind hands every mapped prop on, so an icon with no `fill-*` class',
    ' * would get fill={undefined} -- which react-native-svg draws solid black.',
    " * lucide's own default is no fill; keep it unless a class asks otherwise.",
    ' */',
    'function outlined(Glyph: ComponentType<GlyphProps>): ComponentType<LucideProps> {',
    "  return function Icon({ fill, focusable: _focusable, 'aria-hidden': _hidden, ...props }: LucideProps) {",
    "    return createElement(Glyph, { ...props, fill: fill ?? 'none' });",
    '  };',
    '}',
    '',
    'const fromClassName = {',
    "  size: { fromClassName: 'className', styleProperty: 'width' },",
    "  color: { fromClassName: 'className', styleProperty: 'color' },",
    "  fill: { fromClassName: 'className', styleProperty: 'fill' },",
    '} as const;',
    '',
    ...names.map(
      (name) => `export const ${name} = withUniwind(outlined(${name}Glyph), fromClassName);`,
    ),
    names.length === 0 ? 'export {};' : '',
  );
  return `${lines.join('\n')}\n`;
}
