import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import ts from 'typescript';
import { MARKERS } from './classify.mjs';
import { nativePathFor } from './rules.mjs';

/**
 * The web route registry, read from its AST: every `{ path, lazy: () =>
 * import('@/modules/...'), meta: { titleKey } }` entry.
 */
export function readRoutes(webRoot) {
  const path = join(webRoot, 'src/config/routes.ts');
  if (!existsSync(path)) return [];
  const file = ts.createSourceFile(path, readFileSync(path, 'utf8'), ts.ScriptTarget.Latest, true);
  const routes = [];

  const literal = (node) => (node && ts.isStringLiteralLike(node) ? node.text : null);
  const property = (object, name) =>
    object.properties.find(
      (p) =>
        ts.isPropertyAssignment(p) && p.name && ts.isIdentifier(p.name) && p.name.text === name,
    );

  const visit = (node) => {
    if (ts.isObjectLiteralExpression(node)) {
      const pathProp = property(node, 'path');
      const lazyProp = property(node, 'lazy');
      const routePath = pathProp ? literal(pathProp.initializer) : null;
      if (routePath && lazyProp) {
        let module = null;
        const findImport = (child) => {
          if (
            ts.isCallExpression(child) &&
            child.expression.kind === ts.SyntaxKind.ImportKeyword &&
            child.arguments[0]
          )
            module = literal(child.arguments[0]);
          ts.forEachChild(child, findImport);
        };
        findImport(lazyProp.initializer);
        const metaProp = property(node, 'meta');
        let titleKey = null;
        let permission = null;
        if (metaProp && ts.isObjectLiteralExpression(metaProp.initializer)) {
          titleKey = literal(property(metaProp.initializer, 'titleKey')?.initializer);
          permission = literal(property(metaProp.initializer, 'permission')?.initializer);
        }
        routes.push({ path: routePath, module, titleKey, permission });
        return;
      }
    }
    ts.forEachChild(node, visit);
  };
  visit(file);
  return routes;
}

/**
 * `/orders/:orderId` -> `src/app/orders/[orderId].tsx`.
 *
 * A path that is also a PREFIX of another route becomes `index.tsx` inside its
 * folder (`/orders` -> `orders/index.tsx`), so `orders/[orderId].tsx` can sit
 * beside it -- the layout Expo Router expects for a list and its detail.
 */
export function expoRouteFile(path, allPaths) {
  if (path === '/' || path === '') return 'src/app/index.tsx';
  const segments = path
    .replace(/^\//, '')
    .replace(/\/$/, '')
    .split('/')
    .map((segment) => {
      if (segment === '*') return '[...rest]';
      if (segment.startsWith(':')) return `[${segment.slice(1).replace(/\?$/, '')}]`;
      return segment;
    });
  const isPrefix = allPaths.some((other) => other !== path && other.startsWith(`${path}/`));
  return isPrefix ? `src/app/${segments.join('/')}/index.tsx` : `src/app/${segments.join('/')}.tsx`;
}

/** `@/modules/a/b/b-page` -> `src/modules/a/b/b-page.tsx` (or .ts), on the web side. */
export function moduleFile(webRoot, module) {
  if (!module?.startsWith('@/')) return null;
  const base = `src/${module.slice(2)}`;
  return ['.tsx', '.ts', '/index.tsx', '/index.ts']
    .map((ext) => `${base}${ext}`)
    .find((candidate) => existsSync(join(webRoot, candidate)));
}

/** `src/screens/home.tsx` -> `@/screens/home` */
const importPath = (rel) => `@/${rel.replace(/^src\//, '').replace(/(\/index)?\.tsx?$/, '')}`;

/**
 * The screen file for one route. Until its page is translated it renders a
 * placeholder -- importing the web page would pull DOM markup into the bundle
 * and break the build for every OTHER screen too.
 */
export function routeFileSource(route, pageRel, pageReady) {
  // `nav:home` -> useTranslation('nav') + t('home'): the typed `t` accepts a
  // key of the namespace it was given, not the prefixed form.
  const [ns, key] = route.titleKey?.includes(':')
    ? route.titleKey.split(/:(.*)/s)
    : [null, route.titleKey];
  const title = route.titleKey ? `\n      <Stack.Screen options={{ title: t('${key}') }} />` : '';
  const tImport = route.titleKey ? "import { useTranslation } from 'react-i18next';\n" : '';
  const tHook = route.titleKey ? `  const { t } = useTranslation(${ns ? `'${ns}'` : ''});\n` : '';
  const guard = route.permission
    ? `\n// The web route requires '${route.permission}'. Guard it in a layout (see PORT.md, "Shell").`
    : '';

  if (pageReady) {
    return `// react-dev:route generated by \`npm run port\` from the web route '${route.path}'.${guard}
import { Stack } from 'expo-router';
${tImport}import Page from '${importPath(pageRel)}';

export default function Route() {
${tHook}  return (
    <>${title}
      <Page />
    </>
  );
}
`;
  }
  return `// ${MARKERS.routeStub} -- '${route.path}' is not translated yet. \`npm run port\` swaps in the
// real page once ${pageRel ?? 'its page'} is native. Do not edit: this file is regenerated.${guard}
import { Stack } from 'expo-router';
${tImport}import { PortStub } from '@/platform/port-stub';

export default function Route() {
${tHook}  return (
    <>${title}
      <PortStub path="${route.path}" page="${pageRel ?? 'unknown'}" />
    </>
  );
}
`;
}

export { nativePathFor };
