import { existsSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import postcss from 'postcss';

/**
 * The web app's design tokens, in the form Uniwind reads.
 *
 * The web declares tokens the shadcn way: `@theme inline` maps utilities to
 * variables, `:root` holds the light values, `.dark` overrides them, and named
 * themes are `[data-theme='x']` blocks combined with `.dark`. Uniwind has one
 * flat list of themes, each declared in full under `@layer theme { :root {
 * @variant <name> { ... } } }`. So the grid of theme x scheme becomes a list:
 * light, dark, clay, clay-dark, ... -- each one the merge of every block that
 * applies to it, because Uniwind wants every theme to define every variable.
 *
 * The `@theme` blocks (and `@utility`) are carried over untouched: utility
 * class names are what the copied markup uses, and keeping them identical is
 * what lets `bg-card rounded-card` mean the same thing on both sides.
 */

export const TOKENS_HEADER =
  '/* react-dev:generated by `npm run port` from the web app stylesheets. Edit those and re-run the port. */';

/** Inline local `@import './x.css'`, so themes.css counts as part of index.css. */
function load(path, seen = new Set()) {
  if (seen.has(path) || !existsSync(path)) return postcss.root();
  seen.add(path);
  const root = postcss.parse(readFileSync(path, 'utf8'), { from: path });
  root.walkAtRules('import', (rule) => {
    const target = rule.params
      .replace(/^url\(|\)$/g, '')
      .replace(/['"]/g, '')
      .trim();
    if (target.startsWith('.')) {
      const child = load(join(dirname(path), target), seen);
      rule.replaceWith(child.nodes);
    }
  });
  return root;
}

/**
 * What a selector says about where its variables apply, or null when it is a
 * shape this conversion does not understand (a descendant combinator, an
 * element) -- reported, never guessed at.
 */
export function parseSelector(selector) {
  let rest = selector
    .trim()
    .replace(/^:root/, '')
    .replace(/^html/, '');
  let theme = null;
  const schemes = [];
  const attribute = /\[data-theme\s*=\s*(['"]?)([\w-]+)\1\]/;
  for (;;) {
    rest = rest.trim();
    if (rest === '') break;
    // `[data-theme]` with no value: "whichever named theme is active".
    if (rest.startsWith('[data-theme]')) {
      theme = '*';
      rest = rest.slice('[data-theme]'.length);
      continue;
    }
    const themeMatch = rest.match(new RegExp(`^${attribute.source}`));
    if (themeMatch) {
      theme = themeMatch[2];
      rest = rest.slice(themeMatch[0].length);
      continue;
    }
    const classMatch = rest.match(/^\.([\w-]+)/);
    if (classMatch) {
      schemes.push(classMatch[1]);
      rest = rest.slice(classMatch[0].length);
      continue;
    }
    if (rest.startsWith(':root')) {
      rest = rest.slice(5);
      continue;
    }
    return null;
  }
  if (schemes.length > 1) return null;
  return { theme: theme ?? 'default', scheme: schemes[0] ?? 'light' };
}

export function variantName(theme, scheme) {
  if (theme === 'default') return scheme;
  return scheme === 'light' ? theme : `${theme}-${scheme}`;
}

export function convertTokens(webRoot) {
  const entry = join(webRoot, 'src/styles/index.css');
  const root = load(entry);
  const dropped = [];
  const keep = [];
  /** `${theme}|${scheme}` -> Map(variable -> value) */
  const blocks = new Map();

  const addVars = (theme, scheme, rule) => {
    const key = `${theme}|${scheme}`;
    const vars = blocks.get(key) ?? new Map();
    rule.walkDecls(/^--/, (decl) => {
      vars.set(decl.prop, decl.value);
    });
    blocks.set(key, vars);
  };

  for (const node of root.nodes) {
    if (node.type === 'comment') continue;
    if (node.type === 'atrule') {
      if (node.name === 'theme' || node.name === 'utility') {
        keep.push(node.clone());
      } else if (node.name === 'import') {
        if (!/tailwindcss/.test(node.params)) dropped.push(`@import ${node.params}`);
      } else {
        dropped.push(`@${node.name} ${node.params}`.trim());
      }
      continue;
    }
    if (node.type === 'rule') {
      const hasVars = node.nodes.some(
        (child) => child.type === 'decl' && child.prop.startsWith('--'),
      );
      const targets = node.selectors.map(parseSelector);
      if (!hasVars || targets.some((target) => target === null)) {
        dropped.push(`${node.selector} { … }`);
        continue;
      }
      for (const target of targets) addVars(target.theme, target.scheme, node);
    }
  }

  // `default` first: it is the base every other theme is merged over, and the
  // order here is the order a theme switcher lists them in.
  const named = [...new Set([...blocks.keys()].map((key) => key.split('|')[0]))].filter(
    (theme) => theme !== '*',
  );
  const themes = ['default', ...named.filter((theme) => theme !== 'default')];
  const schemes = [...new Set(['light', ...[...blocks.keys()].map((key) => key.split('|')[1])])];
  const get = (theme, scheme) => blocks.get(`${theme}|${scheme}`) ?? new Map();

  const variants = [];
  for (const theme of themes) {
    for (const scheme of schemes) {
      // A named theme that never mentions a scheme still gets one: its light
      // values over the base scheme's -- the same cascade the browser applies.
      const merged = new Map([
        ...get('default', 'light'),
        ...get('default', scheme),
        ...get(theme, 'light'),
        ...(theme === 'default' ? [] : get('*', scheme)),
        ...get(theme, scheme),
      ]);
      variants.push({ name: variantName(theme, scheme), theme, scheme, vars: merged });
    }
  }

  // Uniwind warns when themes disagree on which variables exist. The merge
  // above makes them agree whenever the base declares everything; report the
  // rest instead of inventing a value.
  const all = new Set(variants.flatMap((variant) => [...variant.vars.keys()]));
  const gaps = [];
  for (const variant of variants)
    for (const name of all) if (!variant.vars.has(name)) gaps.push(`${variant.name}: ${name}`);

  const out = [TOKENS_HEADER, ''];
  for (const node of keep) out.push(node.toString(), '');
  out.push('@layer theme {', '  :root {');
  for (const variant of variants) {
    out.push(`    @variant ${variant.name} {`);
    for (const [name, value] of variant.vars) out.push(`      ${name}: ${value};`);
    out.push('    }');
  }
  out.push('  }', '}', '');

  return {
    css: out.join('\n'),
    extraThemes: variants
      .map((variant) => variant.name)
      .filter((name) => name !== 'light' && name !== 'dark'),
    themes,
    schemes,
    dropped,
    gaps,
  };
}
