/**
 * PORT.md: what is left, in the order it is worth doing.
 *
 * Re-derived on every run from the two codebases -- never edited by hand and
 * never trusted as state. A checkbox here is ticked because the native file is
 * there and passes the same checks as everything else, not because someone
 * remembered to tick it.
 */

const READY = new Set(['done', 'unstamped']);

function isLeft(entry) {
  return (
    (entry.status === 'translate' && !READY.has(entry.nativeState)) || entry.status === 'blocked'
  );
}

/** Every file a page pulls in that still needs work, deepest first. */
export function remainingFor(rel, entries) {
  const seen = new Set();
  const order = [];
  const visit = (current) => {
    if (seen.has(current)) return;
    seen.add(current);
    const entry = entries.get(current);
    if (!entry) return;
    for (const dep of entry.deps) visit(dep.target);
    if (isLeft(entry)) order.push(entry);
  };
  visit(rel);
  return order;
}

const box = (done) => (done ? '[x]' : '[ ]');

function stateLabel(entry) {
  switch (entry.nativeState) {
    case 'done':
    case 'unstamped':
      return 'done';
    case 'stale':
      return 'STALE -- the web file is not the version this translation follows';
    case 'in-progress':
      return `in progress -- still ${entry.nativeProblems.join('; ')}`;
    default:
      return 'todo';
  }
}

export function renderWorklist({
  webName,
  webRoot,
  when,
  entries,
  routes,
  copyResults,
  tokens,
  depChanges,
  shellNotes,
}) {
  const all = [...entries.values()];
  const by = (predicate) => all.filter(predicate);
  const source = by((e) => !e.isTest);
  const copied = source.filter((e) => e.status === 'copy');
  const copiedTests = by((e) => e.isTest && e.status === 'copy');
  const translate = source.filter((e) => e.status === 'translate');
  const translated = translate.filter((e) => READY.has(e.nativeState));
  const blocked = source.filter((e) => e.status === 'blocked');
  const stale = translate.filter((e) => e.nativeState === 'stale');
  const diverged = copyResults.filter((r) => r.action === 'diverged');
  const screensDone = routes.filter((r) => r.ready).length;

  const lines = [
    `# Port worklist -- ${webName} -> native`,
    '',
    `Generated by \`npm run port\` from \`${webRoot}\` on ${when}. Every line below is`,
    're-derived from both codebases on each run: do not edit this file, change the code',
    'and run the port again.',
    '',
    '|                          |  Files | What it means                                         |',
    '| ------------------------ | -----: | ----------------------------------------------------- |',
    `| Copied verbatim          | ${String(copied.length).padStart(6)} | logic, data, schemas, API, mocks -- the web's own code |`,
    `| Web tests copied         | ${String(copiedTests.length).padStart(6)} | run by \`npm run test:logic\` against the copied code   |`,
    `| Translated               | ${String(`${translated.length}/${translate.length}`).padStart(6)} | UI and browser code rewritten for React Native        |`,
    `| Blocked                  | ${String(blocked.length).padStart(6)} | portable, but imports something not translated yet    |`,
    `| Screens live             | ${String(`${screensDone}/${routes.length}`).padStart(6)} | routes whose page is native (the rest show a stub)    |`,
    `| Stale translations       | ${String(stale.length).padStart(6)} | the web file moved on from the version translated     |`,
    `| Diverged copies          | ${String(diverged.length).padStart(6)} | edited here AND changed on the web -- merge by hand    |`,
    '',
  ];

  if (depChanges.length > 0) {
    lines.push('## Dependencies changed -- run `npm install`', '');
    for (const change of depChanges) lines.push(`- ${change}`);
    lines.push('');
  }

  const platform = translate.filter((e) => !e.rel.endsWith('.tsx') && !READY.has(e.nativeState));
  if (platform.length > 0) {
    lines.push(
      '## 1. Platform code first',
      '',
      'Logic that touches the browser or a web-only package. Small files, and each one',
      'unblocks many others -- do these before any screen.',
      '',
    );
    for (const entry of platform)
      lines.push(
        `- ${box(false)} \`${entry.native}\` -- ${entry.reasons.join('; ')} (${stateLabel(entry)})`,
      );
    lines.push('');
  }

  const shared = translate.filter(
    (e) => e.rel.startsWith('src/components/') && e.rel.endsWith('.tsx'),
  );
  if (shared.length > 0) {
    const layers = ['atoms', 'molecules', 'organisms', 'templates'];
    lines.push(
      '## 2. Shared components, atoms first',
      '',
      'Every screen is built from these. Translate a layer before the one above it.',
      '',
    );
    for (const layer of layers) {
      const items = shared.filter((e) => e.rel.startsWith(`src/components/${layer}/`));
      if (items.length === 0) continue;
      const done = items.filter((e) => READY.has(e.nativeState)).length;
      lines.push(`### ${layer} (${done}/${items.length})`, '');
      for (const entry of items)
        lines.push(
          `- ${box(READY.has(entry.nativeState))} \`${entry.native}\` -- ${stateLabel(entry)}`,
        );
      lines.push('');
    }
  }

  lines.push(
    '## 3. Screens, in registry order',
    '',
    'One screen per pass. The count is every untranslated file the page pulls in;',
    'translate them deepest first, run `npm run port`, and the route switches from its',
    'stub to the real page by itself.',
    '',
  );
  for (const route of routes) {
    const left = route.pageRel ? remainingFor(route.pageRel, entries) : [];
    lines.push(
      `- ${box(route.ready)} \`${route.path}\` -> \`${route.file}\`` +
        (route.pageRel ? ` <- \`${route.pageNative}\`` : ' (page module not found)') +
        (route.ready ? '' : ` -- ${left.length} file(s) left`) +
        (route.permission ? ` -- needs \`${route.permission}\`` : ''),
    );
    if (!route.ready)
      for (const entry of left.slice(0, 12))
        lines.push(
          `  - \`${entry.native}\` -- ${entry.status === 'blocked' ? 'blocked' : stateLabel(entry)}`,
        );
    if (left.length > 12) lines.push(`  - ... and ${left.length - 12} more`);
  }
  lines.push('');

  // Whatever the three sections above did not list: UI no route reaches yet
  // (a not-found page, a dialog opened from code), so nothing is silently lost.
  const listed = new Set([
    ...platform.map((e) => e.rel),
    ...shared.map((e) => e.rel),
    ...routes.flatMap((route) =>
      route.pageRel ? remainingFor(route.pageRel, entries).map((e) => e.rel) : [],
    ),
  ]);
  const rest = translate.filter((e) => !listed.has(e.rel) && !READY.has(e.nativeState));
  if (rest.length > 0) {
    lines.push('## 4. Everything else to translate', '', 'UI that no route reaches directly.', '');
    for (const entry of rest)
      lines.push(
        `- ${box(false)} \`${entry.native}\` -- ${entry.reasons.join('; ')} (${stateLabel(entry)})`,
      );
    lines.push('');
  }

  if (stale.length > 0) {
    lines.push(
      '## Stale translations',
      '',
      'Port the web change (`git diff` the web file), then mark it current:',
      '`npm run port -- --done <file>`.',
      '',
    );
    for (const entry of stale) lines.push(`- [ ] \`${entry.native}\` <- \`${entry.rel}\``);
    lines.push('');
  }

  if (diverged.length > 0) {
    lines.push(
      '## Diverged copies',
      '',
      'Changed on both sides since the last port. Merge by hand.',
      '',
    );
    for (const result of diverged) lines.push(`- [ ] \`${result.rel}\``);
    lines.push('');
  }

  lines.push(
    '## Shell -- the web frame, re-implemented as Expo Router layouts',
    '',
    "Not copied: `src/app/` is Expo Router's routes folder, where any file becomes a",
    'screen. What each web file did, and where it goes on native:',
    '',
  );
  for (const note of shellNotes) lines.push(`- \`${note.rel}\` -- ${note.hint}`);
  lines.push('');

  if (tokens.dropped.length > 0 || tokens.gaps.length > 0) {
    lines.push('## Styles not carried over', '');
    for (const item of tokens.dropped)
      lines.push(`- \`${item.replace(/\s+/g, ' ').slice(0, 90)}\``);
    for (const gap of tokens.gaps) lines.push(`- missing variable ${gap}`);
    lines.push(
      '',
      'Fonts are not in the stylesheet on native: load them with `expo-font` in',
      '`src/app/_layout.tsx`, under the family names the tokens use.',
      '',
    );
  }

  const blockedOnly = blocked.filter((e) => !e.rel.includes('/components/'));
  if (blockedOnly.length > 0) {
    lines.push('## Blocked (they copy themselves once their imports are native)', '');
    for (const entry of blockedOnly.slice(0, 60))
      lines.push(`- \`${entry.rel}\` -- ${entry.reasons[0]}`);
    if (blockedOnly.length > 60) lines.push(`- ... and ${blockedOnly.length - 60} more`);
    lines.push('');
  }

  return `${lines.join('\n')}\n`;
}
