// react-dev:generated by `npm run port` from the web app. Edit the web file and re-run the port.
import { z } from 'zod';

/**
 * Expo inlines `process.env.EXPO_PUBLIC_X` -- written out literally -- at build time.
 * The keys keep their web names so every copied file reads them unchanged.
 */
const expoEnv = {
  VITE_API_TIMEOUT_MS: process.env.EXPO_PUBLIC_API_TIMEOUT_MS,
  VITE_API_URL: process.env.EXPO_PUBLIC_API_URL,
  VITE_API_URLS: process.env.EXPO_PUBLIC_API_URLS,
};
/**
 * Environment is validated once, at startup, so a misconfigured deploy fails
 * immediately with a readable message instead of surfacing as `undefined` deep
 * inside a request three screens later.
 */
const url = z.string().url();

/**
 * Extra APIs, as a JSON object of name -> base URL:
 *
 *   VITE_API_URLS={"auth":"https://auth.example.com","payments":"https://pay.example.com"}
 *
 * Adding a backend is an .env change and nothing else -- no new variable to
 * declare here, no new export in api-client.ts. The names are validated as URLs
 * at startup like everything else, so a typo fails the boot rather than the
 * first request that happens to use it.
 */
const extraApis = z
  .string()
  .optional()
  .transform((raw, ctx) => {
    if (raw === undefined || raw.trim() === '') return {};
    try {
      return JSON.parse(raw) as unknown;
    } catch {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: 'must be a JSON object, e.g. {"auth":"https://auth.example.com"}',
      });
      return z.NEVER;
    }
  })
  .pipe(z.record(url));

const schema = z.object({
  VITE_API_URL: url,
  VITE_API_URLS: extraApis,
  VITE_API_TIMEOUT_MS: z.coerce.number().int().positive().default(15_000),
});

const parsed = schema.safeParse(expoEnv);

if (!parsed.success) {
  const issues = parsed.error.issues.map((i) => `  ${i.path.join('.')}: ${i.message}`).join('\n');
  throw new Error(
    `Invalid environment configuration:\n${issues}\n\n` +
      'Development defaults live in .env.development; copy .env.example to ' +
      '.env.local for personal overrides, and configure these in your deployment.',
  );
}

export const env = parsed.data;
